repos:
  - repo: local
    hooks:
    - id: unittest
      name: unittest
      stages: [commit]
      language: system
      entry: coverage run --source ./ -m unittest discover
      types: [python]
      pass_filenames: false

    - id: coverage
      name: coverage
      stages: [push]
      language: system
      entry: coverage report -m --fail-under=80
      types: [python]
      pass_filenames: false

    - id: black
      name: black
      stages: [commit]
      language: system
      entry: black .
      types: [python]

    - id: flake8
      name: flake8
      stages: [commit]
      language: system
      entry: pflake8
      types: [python]
